create extension if not exists "uuid-ossp"; create extension if not exists "pgcrypto";
create type type_offre as enum ('stage_pfe', 'stage_ete', 'emploi_junior', 'alternance');
create type filiere as enum ('informatique', 'genie_civil', 'electrique', 'mecanique', 'gestion', 'finance', 'droit', 'medecine', 'agronomie', 'autre');
create type ville as enum ('nouakchott', 'nouadhibou', 'kaedi', 'rosso', 'aleg', 'autre');
create type source_type as enum ('linkedin', 'entreprise', 'anpe', 'universite', 'whatsapp', 'autre');
create table offres (id uuid primary key default uuid_generate_v4(), source source_type not null, source_name text not null, source_url text unique not null, titre text not null, entreprise text not null, ville ville not null default 'nouakchott', filieres_cibles filiere[] not null default '{}', type_offre type_offre not null default 'stage_pfe', description text, date_limite date not null, contact_email text, contact_whatsapp text, date_scrape date default current_date, active boolean default true, metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create index idx_offres_active_limite on offres(active, date_limite) where active = true;
create index idx_offres_filieres on offres using gin(filieres_cibles); create index idx_offres_source on offres(source, source_name);
create table profils (id uuid primary key default uuid_generate_v4(), telephone text unique not null, nom text not null, prenom text not null, email text, universite text not null, filiere filiere not null, niveau text not null, ville ville not null default 'nouakchott', types_recherches type_offre[] not null default array['stage_pfe']::type_offre[], filieres_interet filiere[] not null default '{}', optin_at timestamptz, optin_texte text, actif boolean default true, date_inscription date default current_date, preferences_notif jsonb default '{"horaire": "09:00", "freq": "quotidien"}', metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table matches (id uuid primary key default uuid_generate_v4(), offre_id uuid not null references offres(id) on delete cascade, profil_id uuid not null references profils(id) on delete cascade, score int not null default 100, notifie boolean default false, date_notification timestamptz, date_match date default current_date, metadata jsonb default '{}', unique(offre_id, profil_id));
create index idx_matches_profil_notifie on matches(profil_id, notifie) where notifie = false; create index idx_matches_offre on matches(offre_id);
create table scraper_logs (id uuid primary key default uuid_generate_v4(), source source_type not null, source_name text not null, status text not null, offres_nouvelles int default 0, offres_total int default 0, error_message text, duration_ms int, created_at timestamptz default now());
alter table offres enable row level security; alter table profils enable row level security; alter table matches enable row level security; alter table scraper_logs enable row level security;
create policy "public_read_active_offres" on offres for select using (active = true and date_limite >= current_date);
create policy "service_role_all_offres" on offres for all using (auth.role() = 'service_role');
create policy "service_role_all_profils" on profils for all using (auth.role() = 'service_role');
create policy "service_role_all_matches" on matches for all using (auth.role() = 'service_role');
create policy "service_role_all_logs" on scraper_logs for all using (auth.role() = 'service_role');
create policy "user_own_profil" on profils for select using (auth.uid() = id);
create policy "user_own_matches" on matches for select using (auth.uid() = profil_id);
create or replace function update_updated_at_column() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end $$;
create trigger update_offres_updated_at before update on offres for each row execute function update_updated_at_column();
create trigger update_profils_updated_at before update on profils for each row execute function update_updated_at_column();